#!/bin/bash

# PHASE 5 QUICK START SCRIPT
# For deployment engineers - execute deployment in ~2 hours

echo "================================================================================"
echo "              PHASE 5: PRODUCTION DEPLOYMENT - QUICK START"
echo "================================================================================"
echo ""
echo "Card Benefits Tracker | Production Deployment to Railway"
echo "Status: ✅ READY FOR DEPLOYMENT"
echo ""
echo "Estimated Time: 1.5-2 hours for complete deployment + verification"
echo ""
echo "================================================================================"
echo "                         STEP 0: PRE-REQUISITES"
echo "================================================================================"
echo ""
echo "Before starting, make sure you have:"
echo ""
echo "  [ ] Read: PHASE5_EXECUTIVE_SUMMARY.md (10 min)"
echo "  [ ] Read: PHASE5_DEPLOYMENT_GUIDE.md sections 1-3 (15 min)"
echo "  [ ] Railway account created at: https://railway.app"
echo "  [ ] Git repository cloned and main branch checked out"
echo "  [ ] Terminal access with git and ability to push"
echo ""
echo "================================================================================"
echo "                    STEP 1: GENERATE PRODUCTION SECRETS"
echo "================================================================================"
echo ""
echo "Generate the required secrets for production:"
echo ""
echo "  1. Generate SESSION_SECRET:"
echo "     $ SESSION_SECRET=\$(openssl rand -hex 32)"
echo "     $ echo \$SESSION_SECRET"
echo ""
echo "  2. Generate CRON_SECRET:"
echo "     $ CRON_SECRET=\$(openssl rand -hex 32)"
echo "     $ echo \$CRON_SECRET"
echo ""
echo "  📌 SAVE THESE VALUES - You'll need them in Step 2!"
echo "  ⚠️  NEVER share these or commit them to git!"
echo ""
echo "================================================================================"
echo "                     STEP 2: CREATE RAILWAY PROJECT"
echo "================================================================================"
echo ""
echo "  1. Go to: https://railway.app"
echo "  2. Click: \"New Project\" → \"Deploy from GitHub\""
echo "  3. Select: Card-Benefits repository"
echo "  4. Confirm: main branch"
echo "  5. Authorize: Railway to access GitHub"
echo ""
echo "  Status: Waiting for project creation..."
echo "  ⏱️  Estimated time: 5 minutes"
echo ""
echo "================================================================================"
echo "                    STEP 3: ADD POSTGRESQL DATABASE"
echo "================================================================================"
echo ""
echo "  1. In Railway project dashboard"
echo "  2. Click: \"Add Service\" → \"Database\" → \"PostgreSQL\""
echo "  3. Select: PostgreSQL 15 (version)"
echo "  4. Wait: For database to initialize (~2 minutes)"
echo "  5. Note: The DATABASE_URL (shown in Variables tab)"
echo ""
echo "  Status: DATABASE_URL will auto-populate in Step 4"
echo "  ⏱️  Estimated time: 5 minutes"
echo ""
echo "================================================================================"
echo "                 STEP 4: CONFIGURE ENVIRONMENT VARIABLES"
echo "================================================================================"
echo ""
echo "  In Railway Dashboard → Variables tab:"
echo ""
echo "  1. Add: SESSION_SECRET"
echo "     Value: [Paste from Step 1]"
echo ""
echo "  2. Add: CRON_SECRET"
echo "     Value: [Paste from Step 1]"
echo ""
echo "  3. Add: NODE_ENV"
echo "     Value: production"
echo ""
echo "  4. Add: LOG_LEVEL"
echo "     Value: info"
echo ""
echo "  5. Verify: DATABASE_URL auto-populated? ✓"
echo ""
echo "  📌 ALL VARIABLES MUST BE SET BEFORE DEPLOYING"
echo "  ⏱️  Estimated time: 10 minutes"
echo ""
echo "================================================================================"
echo "                         STEP 5: DEPLOY APPLICATION"
echo "================================================================================"
echo ""
echo "  Choose ONE of the following deployment methods:"
echo ""
echo "  METHOD A: Automatic Git Deployment (Recommended)"
echo "  ────────────────────────────────────────────────"
echo "    \$ git push origin main"
echo "    → Railway automatically builds and deploys"
echo "    → Watch: Railway Dashboard → Deployments tab"
echo ""
echo "  METHOD B: Manual Railway CLI"
echo "  ──────────────────────────"
echo "    \$ railway login"
echo "    \$ railway link"
echo "    \$ railway up"
echo "    → Follow prompts to link project"
echo ""
echo "  METHOD C: Manual Dashboard Redeploy"
echo "  ───────────────────────────────────"
echo "    1. Railway Dashboard → Deployments"
echo "    2. Click: \"Deploy\" button"
echo ""
echo "  After starting deployment:"
echo "    → Check logs: Railway Dashboard → Logs"
echo "    → Wait for: \"Health checks passing\" message"
echo "    → Should complete in: 5-10 minutes"
echo ""
echo "  ⏱️  Estimated time: 10-15 minutes"
echo ""
echo "================================================================================"
echo "                      STEP 6: VERIFY DEPLOYMENT"
echo "================================================================================"
echo ""
echo "  After deployment completes, verify it worked:"
echo ""
echo "  1. Check health endpoint:"
echo "     \$ curl https://[project-name].up.railway.app/api/health"
echo "     → Expected: 200 OK with \"healthy\" status"
echo ""
echo "  2. Check application loads:"
echo "     → Open: https://[project-name].up.railway.app"
echo "     → Should see: Login/signup page"
echo ""
echo "  3. Verify in Railway dashboard:"
echo "     → Deployments tab: Green checkmark?"
echo "     → Metrics tab: CPU <20%, Memory <300MB?"
echo "     → Logs tab: Any errors? (should be none)"
echo ""
echo "  ✅ If all green → DEPLOYMENT SUCCESSFUL!"
echo "  ⏱️  Estimated time: 15-20 minutes"
echo ""
echo "================================================================================"
echo "                   STEP 7: COMPREHENSIVE VERIFICATION"
echo "================================================================================"
echo ""
echo "  Follow verification procedures in:"
echo "  → PHASE5_DEPLOYMENT_GUIDE.md (Section 6: Post-Deployment Verification)"
echo ""
echo "  Complete 6 verification phases:"
echo "    Phase 1: Immediate health checks (5-10 min)"
echo "    Phase 2: Feature verification (10-15 min)"
echo "    Phase 3: Error handling (5 min)"
echo "    Phase 4: Performance baseline (5 min)"
echo "    Phase 5: Monitoring verification (5 min)"
echo "    Phase 6: Data integrity checks (5 min)"
echo ""
echo "  ⏱️  Estimated time: 30-45 minutes"
echo ""
echo "================================================================================"
echo "                        STEP 8: SETUP MONITORING"
echo "================================================================================"
echo ""
echo "  Railway built-in monitoring is active!"
echo "  Optional: Set up external monitoring"
echo ""
echo "  Quick Setup (Highly Recommended):"
echo "    1. UptimeRobot (free tier, 5 min)"
echo "       → Go to: https://uptimerobot.com"
echo "       → Monitor: /api/health endpoint"
echo "       → Alerts: Email + Slack"
echo ""
echo "  For full monitoring setup:"
echo "    → See: MONITORING_SETUP.md"
echo ""
echo "  ⏱️  Estimated time: 5-30 minutes (depending on tools)"
echo ""
echo "================================================================================"
echo "                      STEP 9: ANNOUNCE GO-LIVE"
echo "================================================================================"
echo ""
echo "  1. Notify stakeholders:"
echo "     \"✅ Card Benefits Tracker is now live!\""
echo "     \"📍 URL: https://[project-name].up.railway.app\""
echo ""
echo "  2. Inform users:"
echo "     \"Sign up and start tracking your credit card benefits!\""
echo ""
echo "  3. Activate on-call rotation:"
echo "     \"Application in production, monitoring active\""
echo ""
echo "================================================================================"
echo "                      STEP 10: MONITOR 24 HOURS"
echo "================================================================================"
echo ""
echo "  During first 24 hours:"
echo "    ✓ Monitor logs for errors"
echo "    ✓ Check metrics every 30 minutes"
echo "    ✓ Respond to any alerts immediately"
echo "    ✓ Document any issues encountered"
echo ""
echo "  Use RUNBOOK.md for quick reference:"
echo "    ✓ Critical alerts procedures"
echo "    ✓ Troubleshooting scenarios"
echo "    ✓ Escalation procedures"
echo ""
echo "================================================================================"
echo "                        SUPPORT & HELP"
echo "================================================================================"
echo ""
echo "  If something goes wrong:"
echo ""
echo "  Before deploying:"
echo "    → PRE_DEPLOYMENT_CHECKLIST.md (verify all items)"
echo ""
echo "  During deployment:"
echo "    → PHASE5_DEPLOYMENT_GUIDE.md (Section 9: Troubleshooting)"
echo ""
echo "  After deployment:"
echo "    → RUNBOOK.md (critical alerts & procedures)"
echo "    → OPERATIONS_GUIDE.md (detailed procedures)"
echo ""
echo "  Escalation:"
echo "    → Engineering Lead: [contact info]"
echo "    → DevOps Lead: [contact info]"
echo "    → Railway Support: support@railway.app"
echo ""
echo "================================================================================"
echo "                         TIMELINE SUMMARY"
echo "================================================================================"
echo ""
echo "  Step 0 (Pre-requisites):     25 minutes"
echo "  Step 1 (Generate secrets):    5 minutes"
echo "  Step 2 (Create project):      5 minutes"
echo "  Step 3 (Add database):        5 minutes"
echo "  Step 4 (Env variables):      10 minutes"
echo "  Step 5 (Deploy):            10-15 minutes"
echo "  Step 6 (Verify):            15-20 minutes"
echo "  Step 7 (Comprehensive):     30-45 minutes"
echo "  Step 8 (Monitoring):         5-30 minutes"
echo "  Step 9 (Announce):           5 minutes"
echo "  ────────────────────────────────────────"
echo "  TOTAL:                    1.5-2 hours"
echo ""
echo "================================================================================"
echo "                    🚀 YOU'RE READY TO DEPLOY!"
echo "================================================================================"
echo ""
echo "Next action:"
echo "  1. Read: PHASE5_EXECUTIVE_SUMMARY.md"
echo "  2. Follow: Steps 0-10 above"
echo "  3. Consult: Documentation as needed"
echo ""
echo "Questions? See PHASE5_DOCUMENTATION_INDEX.md for complete guide."
echo ""
echo "================================================================================"
