-- Expand US airports coverage
-- Idempotent: ON CONFLICT ("iata_code") DO NOTHING ensures safe re-runs.
-- IDs are deterministic (md5 of IATA code) so repeated migrations produce
-- identical rows.

INSERT INTO "lounge_airports" ("id", "iata_code", "name", "city", "timezone", "created_at")
VALUES
  (concat('cl', substr(md5('ABQ'), 1, 23)), 'ABQ', 'Albuquerque International Sunport', 'Albuquerque', 'America/Denver', NOW()),
  (concat('cl', substr(md5('ANC'), 1, 23)), 'ANC', 'Ted Stevens Anchorage International Airport', 'Anchorage', 'America/Anchorage', NOW()),
  (concat('cl', substr(md5('ATL'), 1, 23)), 'ATL', 'Hartsfield-Jackson Atlanta International Airport', 'Atlanta', 'America/New_York', NOW()),
  (concat('cl', substr(md5('AUS'), 1, 23)), 'AUS', 'Austin-Bergstrom International Airport', 'Austin', 'America/Chicago', NOW()),
  (concat('cl', substr(md5('BDL'), 1, 23)), 'BDL', 'Bradley International Airport', 'Hartford', 'America/New_York', NOW()),
  (concat('cl', substr(md5('BHM'), 1, 23)), 'BHM', 'Birmingham-Shuttlesworth International Airport', 'Birmingham', 'America/Chicago', NOW()),
  (concat('cl', substr(md5('BNA'), 1, 23)), 'BNA', 'Nashville International Airport', 'Nashville', 'America/Chicago', NOW()),
  (concat('cl', substr(md5('BOI'), 1, 23)), 'BOI', 'Boise Airport', 'Boise', 'America/Boise', NOW()),
  (concat('cl', substr(md5('BOS'), 1, 23)), 'BOS', 'Boston Logan International Airport', 'Boston', 'America/New_York', NOW()),
  (concat('cl', substr(md5('BUR'), 1, 23)), 'BUR', 'Hollywood Burbank Airport', 'Los Angeles', 'America/Los_Angeles', NOW()),
  (concat('cl', substr(md5('BWI'), 1, 23)), 'BWI', 'Baltimore/Washington International Airport', 'Baltimore', 'America/New_York', NOW()),
  (concat('cl', substr(md5('BZN'), 1, 23)), 'BZN', 'Bozeman Yellowstone International Airport', 'Bozeman', 'America/Denver', NOW()),
  (concat('cl', substr(md5('CLE'), 1, 23)), 'CLE', 'Cleveland Hopkins International Airport', 'Cleveland', 'America/New_York', NOW()),
  (concat('cl', substr(md5('CLT'), 1, 23)), 'CLT', 'Charlotte Douglas International Airport', 'Charlotte', 'America/New_York', NOW()),
  (concat('cl', substr(md5('CMH'), 1, 23)), 'CMH', 'John Glenn Columbus International Airport', 'Columbus', 'America/New_York', NOW()),
  (concat('cl', substr(md5('CVG'), 1, 23)), 'CVG', 'Cincinnati/Northern Kentucky International Airport', 'Cincinnati', 'America/Chicago', NOW()),
  (concat('cl', substr(md5('DAL'), 1, 23)), 'DAL', 'Dallas Love Field', 'Dallas', 'America/Chicago', NOW()),
  (concat('cl', substr(md5('DCA'), 1, 23)), 'DCA', 'Ronald Reagan Washington National Airport', 'Washington DC', 'America/New_York', NOW()),
  (concat('cl', substr(md5('DEN'), 1, 23)), 'DEN', 'Denver International Airport', 'Denver', 'America/Denver', NOW()),
  (concat('cl', substr(md5('DFW'), 1, 23)), 'DFW', 'Dallas/Fort Worth International Airport', 'Dallas', 'America/Chicago', NOW()),
  (concat('cl', substr(md5('DTW'), 1, 23)), 'DTW', 'Detroit Metropolitan Wayne County Airport', 'Detroit', 'America/New_York', NOW()),
  (concat('cl', substr(md5('EWR'), 1, 23)), 'EWR', 'Newark Liberty International Airport', 'Newark', 'America/New_York', NOW()),
  (concat('cl', substr(md5('FAT'), 1, 23)), 'FAT', 'Fresno Yosemite International Airport', 'Fresno', 'America/Los_Angeles', NOW()),
  (concat('cl', substr(md5('FLL'), 1, 23)), 'FLL', 'Fort Lauderdale-Hollywood International Airport', 'Fort Lauderdale', 'America/New_York', NOW()),
  (concat('cl', substr(md5('GEG'), 1, 23)), 'GEG', 'Spokane International Airport', 'Spokane', 'America/Los_Angeles', NOW()),
  (concat('cl', substr(md5('GSO'), 1, 23)), 'GSO', 'Piedmont Triad International Airport', 'Greensboro', 'America/New_York', NOW()),
  (concat('cl', substr(md5('HNL'), 1, 23)), 'HNL', 'Daniel K. Inouye International Airport', 'Honolulu', 'Pacific/Honolulu', NOW()),
  (concat('cl', substr(md5('HOU'), 1, 23)), 'HOU', 'William P. Hobby Airport', 'Houston', 'America/Chicago', NOW()),
  (concat('cl', substr(md5('IAD'), 1, 23)), 'IAD', 'Washington Dulles International Airport', 'Washington', 'America/New_York', NOW()),
  (concat('cl', substr(md5('IAH'), 1, 23)), 'IAH', 'George Bush Intercontinental Airport', 'Houston', 'America/Chicago', NOW()),
  (concat('cl', substr(md5('IND'), 1, 23)), 'IND', 'Indianapolis International Airport', 'Indianapolis', 'America/Chicago', NOW()),
  (concat('cl', substr(md5('JAC'), 1, 23)), 'JAC', 'Jackson Hole Airport', 'Jackson', 'America/Denver', NOW()),
  (concat('cl', substr(md5('JAX'), 1, 23)), 'JAX', 'Jacksonville International Airport', 'Jacksonville', 'America/New_York', NOW()),
  (concat('cl', substr(md5('JFK'), 1, 23)), 'JFK', 'John F. Kennedy International Airport', 'New York', 'America/New_York', NOW()),
  (concat('cl', substr(md5('LAS'), 1, 23)), 'LAS', 'Harry Reid International Airport', 'Las Vegas', 'America/Los_Angeles', NOW()),
  (concat('cl', substr(md5('LAX'), 1, 23)), 'LAX', 'Los Angeles International Airport', 'Los Angeles', 'America/Los_Angeles', NOW()),
  (concat('cl', substr(md5('LGB'), 1, 23)), 'LGB', 'Long Beach Airport', 'Los Angeles', 'America/Los_Angeles', NOW()),
  (concat('cl', substr(md5('MCI'), 1, 23)), 'MCI', 'Kansas City International Airport', 'Kansas City', 'America/Chicago', NOW()),
  (concat('cl', substr(md5('MCO'), 1, 23)), 'MCO', 'Orlando International Airport', 'Orlando', 'America/New_York', NOW()),
  (concat('cl', substr(md5('MDW'), 1, 23)), 'MDW', 'Chicago Midway International Airport', 'Chicago', 'America/Chicago', NOW()),
  (concat('cl', substr(md5('MEM'), 1, 23)), 'MEM', 'Memphis International Airport', 'Memphis', 'America/Chicago', NOW()),
  (concat('cl', substr(md5('MIA'), 1, 23)), 'MIA', 'Miami International Airport', 'Miami', 'America/New_York', NOW()),
  (concat('cl', substr(md5('MKE'), 1, 23)), 'MKE', 'Milwaukee Mitchell International Airport', 'Milwaukee', 'America/Chicago', NOW()),
  (concat('cl', substr(md5('MSP'), 1, 23)), 'MSP', 'Minneapolis-Saint Paul International Airport', 'Minneapolis', 'America/Chicago', NOW()),
  (concat('cl', substr(md5('MSY'), 1, 23)), 'MSY', 'Louis Armstrong New Orleans International Airport', 'New Orleans', 'America/Chicago', NOW()),
  (concat('cl', substr(md5('OAK'), 1, 23)), 'OAK', 'Oakland International Airport', 'Oakland', 'America/Los_Angeles', NOW()),
  (concat('cl', substr(md5('OGG'), 1, 23)), 'OGG', 'Kahului Airport', 'Maui', 'Pacific/Honolulu', NOW()),
  (concat('cl', substr(md5('OKC'), 1, 23)), 'OKC', 'Will Rogers World Airport', 'Oklahoma City', 'America/Chicago', NOW()),
  (concat('cl', substr(md5('OMA'), 1, 23)), 'OMA', 'Eppley Airfield', 'Omaha', 'America/Chicago', NOW()),
  (concat('cl', substr(md5('ORD'), 1, 23)), 'ORD', 'O''Hare International Airport', 'Chicago', 'America/Chicago', NOW()),
  (concat('cl', substr(md5('ORF'), 1, 23)), 'ORF', 'Norfolk International Airport', 'Norfolk', 'America/New_York', NOW()),
  (concat('cl', substr(md5('PDX'), 1, 23)), 'PDX', 'Portland International Airport', 'Portland', 'America/Los_Angeles', NOW()),
  (concat('cl', substr(md5('PHL'), 1, 23)), 'PHL', 'Philadelphia International Airport', 'Philadelphia', 'America/New_York', NOW()),
  (concat('cl', substr(md5('PHX'), 1, 23)), 'PHX', 'Phoenix Sky Harbor International Airport', 'Phoenix', 'America/Phoenix', NOW()),
  (concat('cl', substr(md5('PIT'), 1, 23)), 'PIT', 'Pittsburgh International Airport', 'Pittsburgh', 'America/New_York', NOW()),
  (concat('cl', substr(md5('RDU'), 1, 23)), 'RDU', 'Raleigh-Durham International Airport', 'Raleigh', 'America/New_York', NOW()),
  (concat('cl', substr(md5('RIC'), 1, 23)), 'RIC', 'Richmond International Airport', 'Richmond', 'America/New_York', NOW()),
  (concat('cl', substr(md5('RSW'), 1, 23)), 'RSW', 'Southwest Florida International Airport', 'Fort Myers', 'America/New_York', NOW()),
  (concat('cl', substr(md5('SAN'), 1, 23)), 'SAN', 'San Diego International Airport', 'San Diego', 'America/Los_Angeles', NOW()),
  (concat('cl', substr(md5('SAT'), 1, 23)), 'SAT', 'San Antonio International Airport', 'San Antonio', 'America/Chicago', NOW()),
  (concat('cl', substr(md5('SBA'), 1, 23)), 'SBA', 'Santa Barbara Airport', 'Santa Barbara', 'America/Los_Angeles', NOW()),
  (concat('cl', substr(md5('SEA'), 1, 23)), 'SEA', 'Seattle-Tacoma International Airport', 'Seattle', 'America/Los_Angeles', NOW()),
  (concat('cl', substr(md5('SFO'), 1, 23)), 'SFO', 'San Francisco International Airport', 'San Francisco', 'America/Los_Angeles', NOW()),
  (concat('cl', substr(md5('SJC'), 1, 23)), 'SJC', 'San José Mineta International Airport', 'San Jose', 'America/Los_Angeles', NOW()),
  (concat('cl', substr(md5('SLC'), 1, 23)), 'SLC', 'Salt Lake City International Airport', 'Salt Lake City', 'America/Denver', NOW()),
  (concat('cl', substr(md5('SMF'), 1, 23)), 'SMF', 'Sacramento International Airport', 'Sacramento', 'America/Los_Angeles', NOW()),
  (concat('cl', substr(md5('STL'), 1, 23)), 'STL', 'St. Louis Lambert International Airport', 'St. Louis', 'America/Chicago', NOW()),
  (concat('cl', substr(md5('TPA'), 1, 23)), 'TPA', 'Tampa International Airport', 'Tampa', 'America/New_York', NOW()),
  (concat('cl', substr(md5('TUL'), 1, 23)), 'TUL', 'Tulsa International Airport', 'Tulsa', 'America/Chicago', NOW())
ON CONFLICT ("iata_code") DO NOTHING;
