"""Shared US airport IATA lookup with metadata and timezone.

Used by both ``star_alliance_scraper`` and ``oneworld_scraper`` to validate
extracted IATA codes and enrich lounge records with airport metadata.
"""

US_AIRPORTS: dict[str, dict[str, str]] = {
    "ATL": {"name": "Hartsfield-Jackson Atlanta International Airport", "city": "Atlanta", "timezone": "America/New_York"},
    "AUS": {"name": "Austin-Bergstrom International Airport", "city": "Austin", "timezone": "America/Chicago"},
    "BNA": {"name": "Nashville International Airport", "city": "Nashville", "timezone": "America/Chicago"},
    "BOS": {"name": "Boston Logan International Airport", "city": "Boston", "timezone": "America/New_York"},
    "BWI": {"name": "Baltimore/Washington International Airport", "city": "Baltimore", "timezone": "America/New_York"},
    "CLT": {"name": "Charlotte Douglas International Airport", "city": "Charlotte", "timezone": "America/New_York"},
    "CVG": {"name": "Cincinnati/Northern Kentucky International Airport", "city": "Cincinnati", "timezone": "America/Chicago"},
    "DEN": {"name": "Denver International Airport", "city": "Denver", "timezone": "America/Denver"},
    "DFW": {"name": "Dallas/Fort Worth International Airport", "city": "Dallas", "timezone": "America/Chicago"},
    "DTW": {"name": "Detroit Metropolitan Wayne County Airport", "city": "Detroit", "timezone": "America/New_York"},
    "EWR": {"name": "Newark Liberty International Airport", "city": "Newark", "timezone": "America/New_York"},
    "FLL": {"name": "Fort Lauderdale-Hollywood International Airport", "city": "Fort Lauderdale", "timezone": "America/New_York"},
    "HNL": {"name": "Daniel K. Inouye International Airport", "city": "Honolulu", "timezone": "Pacific/Honolulu"},
    "IAD": {"name": "Washington Dulles International Airport", "city": "Washington", "timezone": "America/New_York"},
    "IAH": {"name": "George Bush Intercontinental Airport", "city": "Houston", "timezone": "America/Chicago"},
    "IND": {"name": "Indianapolis International Airport", "city": "Indianapolis", "timezone": "America/Chicago"},
    "JFK": {"name": "John F. Kennedy International Airport", "city": "New York", "timezone": "America/New_York"},
    "LAS": {"name": "Harry Reid International Airport", "city": "Las Vegas", "timezone": "America/Los_Angeles"},
    "LAX": {"name": "Los Angeles International Airport", "city": "Los Angeles", "timezone": "America/Los_Angeles"},
    "MCI": {"name": "Kansas City International Airport", "city": "Kansas City", "timezone": "America/Chicago"},
    "MCO": {"name": "Orlando International Airport", "city": "Orlando", "timezone": "America/New_York"},
    "MDW": {"name": "Chicago Midway International Airport", "city": "Chicago", "timezone": "America/Chicago"},
    "MEM": {"name": "Memphis International Airport", "city": "Memphis", "timezone": "America/Chicago"},
    "MIA": {"name": "Miami International Airport", "city": "Miami", "timezone": "America/New_York"},
    "MKE": {"name": "Milwaukee Mitchell International Airport", "city": "Milwaukee", "timezone": "America/Chicago"},
    "MSP": {"name": "Minneapolis-Saint Paul International Airport", "city": "Minneapolis", "timezone": "America/Chicago"},
    "MSY": {"name": "Louis Armstrong New Orleans International Airport", "city": "New Orleans", "timezone": "America/Chicago"},
    "OAK": {"name": "Oakland International Airport", "city": "Oakland", "timezone": "America/Los_Angeles"},
    "ORD": {"name": "O'Hare International Airport", "city": "Chicago", "timezone": "America/Chicago"},
    "PDX": {"name": "Portland International Airport", "city": "Portland", "timezone": "America/Los_Angeles"},
    "PHL": {"name": "Philadelphia International Airport", "city": "Philadelphia", "timezone": "America/New_York"},
    "PHX": {"name": "Phoenix Sky Harbor International Airport", "city": "Phoenix", "timezone": "America/Phoenix"},
    "PIT": {"name": "Pittsburgh International Airport", "city": "Pittsburgh", "timezone": "America/New_York"},
    "RDU": {"name": "Raleigh-Durham International Airport", "city": "Raleigh", "timezone": "America/New_York"},
    "SAN": {"name": "San Diego International Airport", "city": "San Diego", "timezone": "America/Los_Angeles"},
    "SAT": {"name": "San Antonio International Airport", "city": "San Antonio", "timezone": "America/Chicago"},
    "SEA": {"name": "Seattle-Tacoma International Airport", "city": "Seattle", "timezone": "America/Los_Angeles"},
    "SFO": {"name": "San Francisco International Airport", "city": "San Francisco", "timezone": "America/Los_Angeles"},
    "SJC": {"name": "San José Mineta International Airport", "city": "San Jose", "timezone": "America/Los_Angeles"},
    "SMF": {"name": "Sacramento International Airport", "city": "Sacramento", "timezone": "America/Los_Angeles"},
    "STL": {"name": "St. Louis Lambert International Airport", "city": "St. Louis", "timezone": "America/Chicago"},
    "TPA": {"name": "Tampa International Airport", "city": "Tampa", "timezone": "America/New_York"},
}
